namespace AccessibleMediaController.Core.Configuration;

public enum SettingsTarget
{
    General,
    Language,
    StartupTarget,
    SessionOrder,
    Prefix,
    PrefixTimeout,
    KeyboardProfile,
    ActivateKeyboardProfile,
    DuplicateKeyboardProfile,
    RenameKeyboardProfile,
    DeleteKeyboardProfile,
    ImportKeyboardMap,
    ExportKeyboardMap,
    KeyboardBindings,
    ChangeKeyboardBinding,
    RemoveKeyboardBinding,
    ListFieldOrder,
    ImportExport,
    ImportConfiguration,
    ExportConfiguration,
    ImportFullBackup,
    ExportFullBackup,
    Messages,
    HistoryMessages,
    ArrowSeekMessages,
    PercentageSeekMessages,
    BookmarkNavigationMessages,
    VolumeMessages,
    PlaybackMessages,
    PercentageSeekAnnouncement,
    MessageTemplates,
    Updates
}
