<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RootNamespace>AccessibleMediaController.Windows</RootNamespace>
    <AssemblyName>AccessibleMediaController</AssemblyName>
    <Version>0.1.0-alpha.11</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AccessibleMediaController.Core\AccessibleMediaController.Core.csproj" />
  </ItemGroup>
</Project>
